name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: 'Sync source code'
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Install Dependencies
        uses: msys2/setup-msys2@v2
        with:
          install: mingw-w64-x86_64-meson mingw-w64-x86_64-ninja mingw-w64-x86_64-pkg-config mingw-w64-x86_64-gcc mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_image
      - name: Build Hades
        run: |
          meson build -Dstatic_executable=true --werror
          cd build
          ninja
      - name: Test Hades
        run: |
          cd build
          ./hades --help
      - name: Collect Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hades-win64
          path: build/hades.exe
          if-no-files-found: error

  mac-os:
    runs-on: macos-latest
    steps:
      - name: 'Sync source code'
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Install Dependencies
        run: |
          brew install meson ninja sdl2 sdl2_image
      - name: Build Hades
        run: |
          CFLAGS="-Wno-microsoft-anon-tag" meson build --werror
          cd build
          ninja
      - name: Test Hades
        run: |
          cd build
          ./hades --help
      - name: Collect Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hades-macos
          path: build/hades
          if-no-files-found: error

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: 'Sync source code'
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build libsdl2-dev libsdl2-image-dev
      - name: Build Hades
        run: |
          meson build --werror
          cd build
          ninja
      - name: Test Hades
        run: |
          cd build
          ./hades --help
      - name: Collect Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hades-linux
          path: build/hades
          if-no-files-found: error