name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build libsdl2-dev libreadline-dev libcapstone-dev
      - name: Build Hades
        run: |
          meson build --buildtype=release
          cd build
          ninja
