name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: 'Sync source code'
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Install Dependencies
        uses: msys2/setup-msys2@v2
        with:
          install: make mingw-w64-x86_64-cmake mingw-w64-x86_64-gcc mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_image mingw-w64-x86_64-glew
      - name: Build Hades
        run: |
          cmake --version
          mkdir build
          cd build
          mkdir dll
          cmake \
            .. \
            -G "Unix Makefiles" \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_FLAGS="-s" \
            -DCI_WIN32_PACKAGING=1
          make -j$(nproc)
      - name: Test Hades
        run: |
          cd build
          ./hades --help
      - name: Collect Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hades-win64
          path: |
            build/hades.exe
            build/dll/
          if-no-files-found: error

  mac-os:
    runs-on: macos-latest
    steps:
      - name: 'Sync source code'
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Install Dependencies
        run: |
          brew install sdl2 sdl2_image glew
      - name: Build Hades
        run: |
          cmake --version
          mkdir build
          cd build
          cmake \
            .. \
            -G "Unix Makefiles" \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_FLAGS="-s" \
            -DGLEW_USE_STATIC_LIBS=ON
          make -j$(sysctl -n hw.availcpu)
      - name: Test Hades
        run: |
          cd build
          ./hades --help
      - name: Collect Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hades-macos
          path: build/hades
          if-no-files-found: error

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: 'Sync source code'
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libsdl2-image-dev libglew-dev
      - name: Build Hades
        run: |
          cmake --version
          mkdir build
          cd build
          cmake \
            .. \
            -G "Unix Makefiles" \
            -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)
      - name: Test Hades
        run: |
          cd build
          ./hades --help
      - name: Collect Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hades-linux
          path: build/hades
          if-no-files-found: error